### PR TITLE
Devops479

### PR DESCRIPTION
**Pull request by nfosdick**
This is step one to automate the run of the sync script.  I want to send positive confirmation of the script being run, but for now I want the cron to run.

### CODE REVIEW

**Comment by ghost** [comment]
@nfosdick, can these duplicate commits be squashed together to clean up the commit history?

**Comment by ghost** [comment]
@nfosdick the code looks good, but I assume this has been tested?

**Comment by nfosdick** [comment]
Yes

**Review by ghost — APPROVED** [review]
Looks good!

**Pull request merged**
